#!/usr/bin/env bash

echo Remember the real files are in /default, keep in mind when making relative links

Xaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1) 
Yaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2) 
XOffset=210
YOffset=25
terminal_start_block="#quick terminal"
terminal_end_block="##### END #####"

i3_config='\
  exec --no-startup-id urxvt -name 'metask' -e 'tmux' \n\
  for_window [instance='metask'] floating enable; \n\
  for_window [instance='metask'] move scratchpad; [instance='metask'] scratchpad show; move position ${XOffset}px ${YOffset}px; resize set $(($Xaxis-$XOffset*2))px $(($Yaxis/2))px;  move scratchpad \n\
  bindsym $mod+grave [instance='metask'] scratchpad show'

set -e

CONFIG="install.conf.json"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo Setting up quick terminal
sed -i ':a;N;$!ba;s@'"${terminal_start_block}"'.*\n*'"${terminal_end_block}"'@'"${terminal_start_block}\n${i3_config}\n${terminal_end_block}"'@g' $BASEDIR/default/i3/config
cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
